### ISSUE TITLE
Add to Readme.md minimum useful example

### ISSUE THREAD

**Issue by AskAlexSharov** [AJChapman/formatting#53]
All examples in Readme.md are in GHCi
But real program require `OverloadedStrings` (while Readme.md doesn't say about it)

It's really hard (tried again and again in 4 different days) to start use lib because copy code from `Readme.md` or from https://github.com/chrisdone/formatting/blob/master/src/Formatting/Examples.hs#L20 just doesn't compile

In Monad:
<img width="670" alt="screen shot 2019-02-17 at 12 10 33 pm" src="https://user-images.githubusercontent.com/46885206/52908680-200d8a00-32ad-11e9-9162-dbf9f78433d4.png">

In pure functions: 
<img width="721" alt="screen shot 2019-02-17 at 12 20 14 pm" src="https://user-images.githubusercontent.com/46885206/52908745-69120e00-32ae-11e9-8fc4-6edc558c768e.png">

Minimum example must look like (maybe you know how to make it better): 
``` haskell
{-# LANGUAGE OverloadedStrings #-}

module Lib where

import           Data.Text.Lazy         (Text)
import           Data.Text.Lazy.Builder (Builder)
import           Formatting
import           Formatting.Formatters

t :: Text
t = format ("Person's name is " % text % ", age is " % hex) "Dave" 54
```

And even better to add one more example - how to implement `instance Show` of some class by using `formatting` lib.

**Comment by AJChapman** [comment]
I think the current documentation addresses this concern. It isn't as a single block, but it tells you that you need OverloadedStrings, to import Formatting, etc. Please reopen if you disagree.
