### ISSUE TITLE
Call for maintainer

### ISSUE THREAD

**Issue by chrisdone** [AJChapman/formatting#58]
The formatting package needs a maintainer. I made this package 6 years ago based on the HoleyMonoid package's idea. I thought it would become a staple package for me.

Since then, I have basically never actually used it in a project. It turns out, I don't like the printf-style of doing printing at all, and prefer to just manually append things. As such, it doesn't make sense for me to maintain this package.

Feel free to comment on this issue if you are interested in taking it over, either as an individual or as a group.

**Comment by donatello** [comment]
I'd like to volunteer maintaining this project either by myself or with any others who are also interested. I've used it in some of my projects and would be interested in keeping it working and running smoothly in upcoming compiler versions.

**Comment by iustin** [comment]
I also use the formatting package, so I contribute some small amount of time.

**Comment by AJChapman** [comment]
Any news here? I too would be happy to help.

**Comment by AJChapman** [comment]
I'm doing it!
