### ISSUE TITLE
Regression where shortest displays in scientific notation

### ISSUE THREAD

**Issue by spencerjanssen** [AJChapman/formatting#59]
In older versions of formatting (such as 6.2.5), `format shortest (0.01 :: Double)` would evaluate to `"0.01"`.  In 6.3.7 the same expression evaluates to `"1.0e-2"`.

I believe this was introduced in c5f9492e3d4e5d50c10a3c7cbb8406eb62ad9a81

**Comment by AJChapman** [comment]
Thanks for the report. This is fixed in 7.0.0.
