### ISSUE TITLE
wrong formatting of Word types

### ISSUE THREAD

**Issue by zoranbosnjak** [AJChapman/formatting#62]
`format (left 3 '0') (0::Word8)` gives wrong result `"0-0"`, instead of `"000"`.

Example:
```haskell
$ ghci
GHCi, version 8.6.5: http://www.haskell.org/ghc/  :? for help
Prelude> :m +Formatting
Prelude Formatting> :m +Data.Word
Prelude Formatting Data.Word> format (left 3 '0') (0::Int)
"000"
Prelude Formatting Data.Word> format (left 3 '0') (0::Word8)
"0-0"
```

**Comment by axman6-da** [comment]
Looks like the bug is in `https://github.com/AJChapman/formatting/blob/master/src/Data/Text/Format/Int.hs#L55` which assumes that if `i == minBound`, then the number is negative, which is obviously wrong for `Word{N}`
