### ISSUE TITLE
Build failures with GHC-8.2 and older

### ISSUE THREAD

**Issue by phadej** [AJChapman/formatting#68]
See https://matrix.hackage.haskell.org/#/package/formatting/7.0.0.1/ghc-8.2.2@1602305719

Please make revisions for `7.0.0` and `7.0.0.1` adding appropriate lower bounds.

(I see some CI configuration in this repository, are they used?)

**Comment by AJChapman** [comment]
Thanks for pointing this out. I will investigate. Regarding CI, I was careful to make sure it passed. See https://travis-ci.org/github/AJChapman/formatting. I also tried to get AppVeyor CI working, so far without success but not due to compile failures (https://ci.appveyor.com/project/AJChapman/formatting).

**Comment by phadej** [comment]
https://travis-ci.org/github/AJChapman/formatting/builds/734629183 seems to be failing for GHC-8.2 and older, in the very same way as on `matrix.hackage.haskell.org`.

**Comment by AJChapman** [comment]
Yes, they are now that I've fixed them :)

**Comment by AJChapman** [comment]
Well I tried pretty hard, got >=7.10 working, but in the end decided it wasn't worth it, so we now only support back to 8.4, and the code is a lot cleaner. Fixed in 7.0.0.2, just released.

**Comment by phadej** [comment]
Please make revisions for the old releases, I cannot reopen this issue. https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md#how-can-i-revise-a-package

**Comment by AJChapman** [comment]
Ok, I've made revisions for 7.0.0 and 7.0.0.1, and the matrix (https://matrix.hackage.haskell.org/#/package/formatting) is all green. Sorry for not realising what you were saying until now, and thanks for your patience.
