### ISSUE TITLE
tighten bounds on double-conversion

### ISSUE THREAD

**Issue by vmchale** [AJChapman/formatting#76]
`double-conversion` seems to have changed its API - one now uses `Data.Double.Conversion.Convertable` instead of the old modules.

So `formatting` needs updated bounds on Hackage!

**Comment by AJChapman** [comment]
I've made revisions to all 7.x releases' metadata for `formatting`, e.g: https://hackage.haskell.org/package/formatting-7.1.3/revisions/, updated formatting.cabal in the repo, and created an issue on `double-conversion` here: https://github.com/haskell/double-conversion/issues/30
